package com.jianye.springmvc.entity;
// Generated 2016-6-5 10:23:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.AttributeOverride;
import javax.persistence.AttributeOverrides;
import javax.persistence.Column;
import javax.persistence.EmbeddedId;
import javax.persistence.Entity;
import javax.persistence.Table;

/**
 * AcctRoleAuthority generated by hbm2java
 */
@Entity
@Table(name = "acct_role_authority", catalog = "work")
public class AcctRoleAuthority implements java.io.Serializable {

	private AcctRoleAuthorityId id;

	public AcctRoleAuthority() {
	}

	public AcctRoleAuthority(AcctRoleAuthorityId id) {
		this.id = id;
	}

	@EmbeddedId

	@AttributeOverrides({
			@AttributeOverride(name = "roleId", column = @Column(name = "role_id", nullable = false, length = 36)),
			@AttributeOverride(name = "authorityId", column = @Column(name = "authority_id", nullable = false, length = 36)) })
	public AcctRoleAuthorityId getId() {
		return this.id;
	}

	public void setId(AcctRoleAuthorityId id) {
		this.id = id;
	}

}
