package com.jianye.springmvc.entity;
// Generated 2016-6-5 10:23:59 by Hibernate Tools 5.1.0.Alpha1

import javax.persistence.Column;
import javax.persistence.Embeddable;

/**
 * AcctRoleAuthorityId generated by hbm2java
 */
@Embeddable
public class AcctRoleAuthorityId implements java.io.Serializable {

	private String roleId;
	private String authorityId;

	public AcctRoleAuthorityId() {
	}

	public AcctRoleAuthorityId(String roleId, String authorityId) {
		this.roleId = roleId;
		this.authorityId = authorityId;
	}

	@Column(name = "role_id", nullable = false, length = 36)
	public String getRoleId() {
		return this.roleId;
	}

	public void setRoleId(String roleId) {
		this.roleId = roleId;
	}

	@Column(name = "authority_id", nullable = false, length = 36)
	public String getAuthorityId() {
		return this.authorityId;
	}

	public void setAuthorityId(String authorityId) {
		this.authorityId = authorityId;
	}

	public boolean equals(Object other) {
		if ((this == other))
			return true;
		if ((other == null))
			return false;
		if (!(other instanceof AcctRoleAuthorityId))
			return false;
		AcctRoleAuthorityId castOther = (AcctRoleAuthorityId) other;

		return ((this.getRoleId() == castOther.getRoleId()) || (this.getRoleId() != null
				&& castOther.getRoleId() != null && this.getRoleId().equals(castOther.getRoleId())))
				&& ((this.getAuthorityId() == castOther.getAuthorityId())
						|| (this.getAuthorityId() != null && castOther.getAuthorityId() != null
								&& this.getAuthorityId().equals(castOther.getAuthorityId())));
	}

	public int hashCode() {
		int result = 17;

		result = 37 * result + (getRoleId() == null ? 0 : this.getRoleId().hashCode());
		result = 37 * result + (getAuthorityId() == null ? 0 : this.getAuthorityId().hashCode());
		return result;
	}

}
